version: "3.8"

services:

  iplant-app:
    image: 271217/felix-node-npm
    container_name: iplant-app
    restart: unless-stopped
    volumes:
      - .:/opt
    entrypoint: ["/bin/sh","-c"]
    command:
      - -c
      - |
        export env REACT_NATIVE_PACKAGER_HOSTNAME=fxdev.pt
        npm start
    ports:
      - 19006:19006
      - 19001:19001
      - 19002:19002