version: "3.8"

services:

  iplant-app:
    image: 271217/felix-node-npm
    container_name: iplant-app
    restart: unless-stopped
    volumes:
      - .:/opt
    ports:
      - 19006:19006
      - 19001:19001
      - 19002:19002
      - 3333:3333
      - 3000:3000
      - 3001:3001
      - 5000:5000